// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PickingListsSystem.DataAccess;

#nullable disable

namespace PickingListsSystem.DataAccess.Migrations
{
    [DbContext(typeof(PlsDbContext))]
    [Migration("20230917131604_Material_nullable")]
    partial class Material_nullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PickingListsSystem.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaterialGost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaterialMark")
                        .HasColumnType("int");

                    b.Property<string>("MaterialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaterialRB")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialRH")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialRL")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialType")
                        .HasColumnType("int");

                    b.Property<string>("MaterialUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MaterialV")
                        .HasColumnType("float");

                    b.Property<int?>("MaterialWeight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
